# Generated by Django 3.2.9 on 2021-11-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaka', to='navigation_app.vehicle'),
        ),
    ]
